languageCode = "zh-tw"
title = "Pecky遊樂間 PeckyPlayZone ᕕ ( ᐛ ) ᕗ"
theme = "hugo-bearblog"
author = "Pecky"
copyright = "Copyright © 2021, Pecky."

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[permalinks]
 
  tags = "/blog/:slug"

[params]
  # The "description" of your website. This is used in the meta data of your generated html.
  description = "PeckyPlayZone"

    # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
  # Hint: It's good practise to also put a "favicon.ico"-file into your "static"-folder.
  favicon = "img/branding/logo_tran-48x48.png"

    # Another "title" :-). This one is used as the site_name on the Hugo's internal
  # opengraph structured data template.
  # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
  title = "Pecky遊樂間"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Pecky"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "Blog"
    name = "文章"
    url = "/blog/"
    weight = 20

  [[menu.main]]
    identifier = "portfolio"
    name = "作品集"
    url = "https://peckyhsieh.wixsite.com/peckyhsieh"
    weight = 30
    

  [[menu.main]]
    identifier = "store"
    name = "商品"
    url = "https://www.rakuten.com.tw/shop/peckystudio/"
    weight = 40



# Google Analytics UA number
googleAnalytics = "UA-XXXXXX-X"